### ISSUE TITLE
git_revwalk_next

### ISSUE THREAD

**Issue by kengruven** [bbusching/libgit2#11]
It would be a great help if the documentation included some examples, as I'm having no luck figuring out how to use these functions, or finding anyone who can help.

For example, `git_revwalk_next` wraps the C function of the same name, which takes a `git_oid *` out pointer.  (The C function, that is.  The Racket FFI wrapper doesn't declare this as an "out" pointer.)  From Racket, there's no apparent public interface for creating a new `git_oid *`, as required for many of these libgit2 functions.  I tried using a simple `(malloc _git_oid)`, but `git_revwalk_next` still fails.

Is it possible to use any of the functions here which take a `git_oid`?  Is it possible to create a `git_oid` struct?  How?

**Comment by kengruven** [comment]
With the new version today (thanks!), I was able to get revwalk to loop the correct number of times from my HEAD, and return hashes.  I used `git_oid_fromstr` to make a dummy OID to use as the out pointer.

One catch, so far: in C, `git_revwalk_next` returns `GIT_ITEROVER` to indicate the end of the list, which isn't *exactly* an error, but Racket's binding doesn't seem to understand the distinction.  So when the Racket revwalk hits the end, it writes to stderr:

```
git_revwalk_next: an error occurred;
 the foreign function returned an error code,
 but git_error_last returned a null pointer
  error code: 'GIT_ITEROVER
  error class: #f
  context...:
```

The `GIT_ITEROVER` "error" case doesn't return normally, so there's no opportunity to check the return value to see if it's complete.

I can write a wrapper to deal with most of the messiness of the git_revwalk_* C interface (and I'd be happy to share it when I have it working), but I can't easily un-write from stderr.

**Comment by LiberalArtist** [comment]
Thanks for this report!

> One catch, so far: in C, `git_revwalk_next` returns `GIT_ITEROVER` to indicate the end of the list, which isn't _exactly_ an error, but Racket's binding doesn't seem to understand the distinction. So when the Racket revwalk hits the end, it writes to stderr:
> 
> ```
> git_revwalk_next: an error occurred;
>  the foreign function returned an error code,
>  but git_error_last returned a null pointer
>   error code: 'GIT_ITEROVER
>   error class: #f
>   context...:
> ```
> 
> The `GIT_ITEROVER` "error" case doesn't return normally, so there's no opportunity to check the return value to see if it's complete.
> 

We can definitely handle this better in the Racket binding. I'll try to take a look in the next few days. I expect you are the first person to use these functions! If you have a small-ish test case that currently fails, that would be a help.

> I can write a wrapper to deal with most of the messiness of the git_revwalk_* C interface (and I'd be happy to share it when I have it working), but I can't easily un-write from stderr.

In the mean time, the code is `raise`ing an `exn:fail:contract` rather than writing to stderr itself, so you could use `with-handlers` to catch the exception:

https://github.com/bbusching/libgit2/blob/4f0f4acd77b22e79852e3b643f3df445cef35281/private/base/errors.rkt#L12-L42

(I don't remember offhand if the `exn:fail:libgit2:foreign` struct is public, but I'm inclined to think it should be.)

More broadly, just FYI:

  - We're moving development of this package to https://github.com/libgit2-racket/libgit2. As of a few minutes ago, the package catalog points there; in the next few days, once we've confirmed that builds are working with the new location, we'll prominently point people from this repository to that one.
  - I wanted to make sure you saw the note on the status of this library: https://github.com/bbusching/libgit2/blob/4f0f4acd77b22e79852e3b643f3df445cef35281/scribblings/libgit2.scrbl#L25-L43
    It's great to have users and bug reports! And I hope we are not far from stability: I'd expect "breaking changes" mostly to consist of fixing bugs like this one without worrying about compatibility for uses of the buggy versions. I just want to make sure we're transparent about where things stand so people can make informed decisions.

**Comment by kengruven** [comment]
In the short term, I'm forking /usr/bin/git and parsing the output myself.  So libgit2-racket's challenge is to be easier to use than that.  :-)

In libgit2, it seems you use revwalk by:
 - creating a revwalk object
 - adding/removing any globs/oids/tags/etc you want
 - looping over the lazy sequence of oids it generates

Ideally, I think what I want as an interface in Racket is something that lets me add/remove all these types of things at once, at creation time:

```
(in-git-revs my-repo #:sort 'time
             'HEAD
             "foo/bar/*.json"
             (lambda (commit-id payload) ...)
             (not some-specific-oid-to-skip)
             (not "some-tag"))
```

which I can use with the `for/*` functions, and it delivers a lazy sequence of oids.  I'm not really a Racket programmer, though, so input is welcome.  Would this need a more explicit way to declare what each type of added/removed thing is?  Can a Racket procedure be used as a callback from C?

**Comment by LiberalArtist** [comment]
I've opened https://github.com/libgit2-racket/libgit2/pull/1 with a fix for `git_revwalk_next`. I plan to merge it after tomorrow's package-build has finished successfully from the new repository (at which point we'll also fully move new development over there).

**Comment by LiberalArtist** [comment]
I hope this was fixed by https://github.com/libgit2-racket/libgit2/pull/1

**Comment by kengruven** [comment]
Yes, it works great now -- thanks!

I may have had to uninstall/reinstall the package for it to pick up the new location.

BTW, the callback option for revwalkers seems to work in Racket, though C->Racket callbacks apparently have a number of restrictions (e.g., nothing which may block, which includes all I/O), so doing the filtering inside of libgit2 is not as useful as I thought it would be.
