### ISSUE TITLE
require libgit2 dumps core immediately

### ISSUE THREAD

**Issue by jbclements** [bbusching/libgit2#12]
Hmm.... with the new version of libgit2, evaluating

```
#lang racket
(require libgit2)
```
causes the racket process to immediately dump core on my M1 machine. That ... doesn't sound right? @LiberalArtist , any idea if I'm doing something obviously broken?

**Comment by jbclements** [comment]
Oh... read the dump better:
```
System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGKILL (Code Signature Invalid))
Exception Codes:       UNKNOWN_0x32 at 0x0000000168210000
Exception Codes:       0x0000000000000032, 0x0000000168210000

Termination Reason:    Namespace CODESIGNING, Code 2 Invalid Page

```
sounds like maybe shared libraries all need to be signed now? I'm ... going to have to look into this tomorrow maybe.

**Comment by LiberalArtist** [comment]
> sounds like maybe shared libraries all need to be signed now?

That would be annoying if so. I vaguely remember having looked at it when I did the native packages for Mac and having thought the libraries Racket ships didn't seem to be signed, but it's certainly possible Apple could have changed things since then.

I think I have the necessary registration to get them signed if it does turn out to be necessary.

**Comment by LiberalArtist** [comment]
When it finally runs, the Mac CI job hopefully will tell us more: https://github.com/bbusching/libgit2/actions/runs/5458855110/jobs/9934310302

**Comment by jbclements** [comment]
Well, I can confirm that loading the dynamic lib is what triggers the core dump on this machine:
```
Grossvogel:~/libgit2 (git)-[master]- clements> racket
Welcome to Racket v8.9.0.5 [cs].
> (require ffi/unsafe)
> (ffi-lib "/Users/clements/racket/racket/lib/libgit2.1.4.dylib")
zsh: killed     racket
```

**Comment by jbclements** [comment]
I took a slightly closer look at the `libgit2` dylib and other dylibs associated with other packages, and here's what I get:

```
Grossvogel:~/racket/racket/lib (git)-[master]- clements> codesign -d -v  libgit2.1.4.dylib  
Executable=/Users/clements/racket/racket/lib/libgit2.1.4.dylib
Identifier=libgit2.1.4.3.dylib
Format=Mach-O thin (arm64)
CodeDirectory v=20400 size=10092 flags=0x2(adhoc) hashes=310+2 location=embedded
Signature=adhoc
Info.plist=not bound
TeamIdentifier=not set
Sealed Resources=none
Internal requirements count=0 size=12
Grossvogel:~/racket/racket/lib (git)-[master]- clements> codesign -d -v libportaudio.2.dylib 
Executable=/Users/clements/racket/racket/lib/libportaudio.2.dylib
Identifier=libportaudio.2.dylib
Format=Mach-O universal (x86_64 arm64)
CodeDirectory v=20400 size=1037 flags=0x20002(adhoc,linker-signed) hashes=29+0 location=embedded
Signature=adhoc
Info.plist=not bound
TeamIdentifier=not set
Sealed Resources=none
Internal requirements=none
```
These look pretty similar, but I see that the libportaudio one has a "linker-signed" flag. I'm wondering whether this is related to its being linked on a macos platform? Maybe this is is just a subtle ploy to make people like you buy Apple hardware? :) (or not-smiley, depending on how you feel about Apple's big-brother tactics)

**Comment by jbclements** [comment]
I tried to compile my own version of libgit2, but got wedged on a silly linker issue related to the libiconv library, almost certainly due to the way I have macports installed and/or a bad interaction between macports & the way that the libgit2 library source is laid out. Ugh. I can just grab a libgit2.dylib from macports, and I can confirm that I can load this library using ffi-lib, and I can further confirm that this library has the "linker-signed" flag on it. So I think that fixing this can probably be done by dropping in a version of the dylib compiled on a mac... which probably totally disrupts your build process, forgive my ignorance about guix.

**Comment by LiberalArtist** [comment]
So, the dylibs were compiled on a Mac by Nix: the only steps done on a non-Mac by Guix were using `install_name_tool -id` to remove the `/nix/store/long-hash-here` prefix from the id and `install-name-tool -change` similarly to replace `#px"(?<=\\s)/nix/store/\\S+/libiconv[\\d\\.]*\\.dylib(?=\\s)"` with `"/usr/lib/libiconv.2.dylib"` (it's [this code](https://github.com/LiberalArtist/native-libgit2-pkgs/blob/770b8f2717a4152af0bea8018e8a915dfaf6f574/guix/libgit2-for-racket.scm#L351-L394)).

One thing that occurred to me is that I only have access to aging Intel Macs, and Arm Macs have [some level of additional code signing requirement](https://eclecticlight.co/2020/08/22/apple-silicon-macs-will-require-signed-code/). I surely wanted to test Arm Macs in CI, but maybe they weren't available in Github Actions at the time (if they are now).

From what I read, `dlopen`ing a dylib still isn't supposed to require a *notarized* signature, but maybe it requires an explicit signing step I didn't do. Unless you happen to know, probably Matthew would be the most likely &hellip;

**Comment by jbclements** [comment]
Okay, just tested this on my x86_64 machine running Monterey (macOS 12.6.7), and libgit2 loads fine. The difference could be the intel chip, but I suspect it's the operating system—the arm machine I have is running Ventura. Furthermore, when I ask codesign about the dylib, I get this:
```
pajaro2:~/Library/Racket/8.9/lib clements> codesign -d -v ./libgit2.1.4.dylib 
./libgit2.1.4.dylib: code object is not signed at all
```

I'm going to try the same thing using the x86 binary schlepped over to the (okay actually a different) arm machine, let's see what I get.

**Comment by jbclements** [comment]
Oh! Weird! The arm/Ventura machine *also* reports that the x86_64 dylib file "is not signed at all". I double-checked, and this machine (like the one at home) reports that the arm64 binary has an "adhoc" signature. So it sounds like the intel binary is genuinely lacking a signature that the arm64 one has, and that the signature/header/whatever attached to the arm64 one is preventing it from running.

**Comment by jbclements** [comment]
Okay, yes, got it. I took a minute and actually read the link that you posted, which explicitly distinguishes between intel & arm. So the problem is that the use of `install_name_tool` is altering the bits in the library in a way that makes the signature invalid. The solution—for now at least—is very simple: the resulting dynamic library needs to be re-signed, using 
```
codesign -s - -f libgit2.1.4.dylib
```
The hyphen tells it to apply an ad-hoc signature, and the `-f` tells it to discard the old signature. 

Using this results in a dylib that I can load with ffi-lib, and makes it possible to load the libgit2 library without dumping core. 

I haven't tried moving the dylib to another machine; it's remotely possibly that something signed in this way could only be used locally, but that doesn't seem likely to me. 

I just took a look at the repo containing the native library, and the sense I get is that a pull request directly against that repo would essentially invalidate everything in the "Provenance" section, so I guess it makes more sense to edit the guix build script, and I'm guessing that you can probably do that ... a lot faster than I can? I'm not sure how much work it will be to get a codesign to happen after the `install_name_tool` step. Could be easy?

**Comment by LiberalArtist** [comment]
> So the problem is that the use of `install_name_tool` is altering the bits in the library in a way that makes the signature invalid.

Oh, right, I guess the whole point of code-signing is that tampering with the file should invalidate the signature.

> The solution—for now at least—is very simple: the resulting dynamic library needs to be re-signed, using
> 
> ```
> codesign -s - -f libgit2.1.4.dylib
> ```
> 
> The hyphen tells it to apply an ad-hoc signature, and the `-f` tells it to discard the old signature.
> 
> [&hellip;] I'm not sure how much work it will be to get a codesign to happen after the `install_name_tool` step. Could be easy?

This is helpful, and it reminded me that [Racket implements just enough of `codesign` to do this specific task](https://github.com/racket/racket/blob/912b199e530189cb03c81658754e56f1849c7761/racket/src/mac/codesign.rkt#L4), so hopefully it will be very easy. The only snag is that I reinstalled my OS since I last worked on this, so I get to see whether I adequately documented how to set up a SSH for remote building on the Mac. Probably not going to be a project for tonight, but hopefully in the next day or two.

**Comment by LiberalArtist** [comment]
The good news is I got my local setup configured again pretty easily.

The bad news is that my attempt to use `compiler/private/mach-o` for the signing violated the assertion at https://github.com/racket/racket/blob/912b199e530189cb03c81658754e56f1849c7761/racket/collects/compiler/private/mach-o.rkt#L79 (or, when I tried skipping the removal of the existing signature, https://github.com/racket/racket/blob/912b199e530189cb03c81658754e56f1849c7761/racket/collects/compiler/private/mach-o.rkt#L468):

    starting phase `patch-shared-library'
    check-same: not: 2 6
    Backtrace:
               1 (primitive-load "/gnu/store/dcqcqpgazywzyyf4dxja9mirpkb…")
    In guix/build/utils.scm:
        762:6  0 (invoke "racket" "-e" "(begin (require compiler/private…")
    

Here's my failed attempt: https://github.com/LiberalArtist/native-libgit2-pkgs/commit/93e6733fffe0ab54dcdfd87d45eb8dc1bf9c7d21

I'll investigate further, but probably not tonight.

**Comment by LiberalArtist** [comment]
Ok, I've gotten the build to work by just not checking the "file type" field, and I've pushed it as v0.2 of the native library packages: https://github.com/LiberalArtist/native-libgit2-pkgs

@jbclements, could you see if this works for you on aarch64-macosx?

**Comment by jbclements** [comment]
Okay, that was … harder than it should have been, primarily because of my ignorance about package naming.

Yes, I can confirm that “it works”. Specifically, cloning the repo, checking out commit bafb3927edbb, renaming the directory to libgit2-aarch64-macosx, using pkg install on this directory, and then doing raco pkg install libgit2 results in an installation in which evaluating (require libgit2) does not dump core. From my standpoint, this is clearly better than the current situation.

IIUC, this will be "live" as soon as the catalog picks up the new commits?

**Comment by LiberalArtist** [comment]
> Yes, I can confirm that “it works”. Specifically, cloning the repo, checking out commit bafb3927edbb, renaming the directory to libgit2-aarch64-macosx, using pkg install on this directory, and then doing raco pkg install libgit2 results in an installation in which evaluating (require libgit2) does not dump core. From my standpoint, this is clearly better than the current situation.

Super!

> IIUC, this will be "live" as soon as the catalog picks up the new commits?

Yes, and I'll hit the "refresh all my packages" button now.

**Comment by jbclements** [comment]
Okay, LGTM (I can install from the repo, doesn't seem to crash right away), closing this. Thanks!
