### ISSUE TITLE
Naming convention is blasphemy

### ISSUE THREAD

**Issue by guygastineau** [bbusching/libgit2#7]
Well, that is incendiary, but I certainly don't mean it in any aggressive terms ;)

I expect you intend for the names to coincide more exactly with the names from the C library.  I can understand that.

I was just going to make a couple levels of wrappers to bring things up to a high level.  To do that I started writing a wrapper generator, but I soon realized that the naming conventions that appear so uniform in the Scribble docs are not the only exported bindings!

What's more I have discovered lisp-style naming conventions interspersed with the C naming conventions.  This makes it very difficult to write tools for generating name change wrappers and other conveniences.

I am still just diving into the code base here, but I am very motivated to restructure the layers of abstraction on top of C.  I want to reach out to learn about existing contributors' ideas and opinions about this.  If you all are still eager for this project to be active, then I will try to do work and fold it back into your project in PR's.  If the consensus is to keep things more stable, then I will probably develop my fork into a fairly different looking project.

Anyway, I look forward to everyone's perspective and experience regarding this package and its future.

**Comment by guygastineau** [comment]
Example of mixed naming conventions:

``` racket
list->git_blame_hunk
set-git_blame_hunk-final_start_line_number!
```

It seems to me like these should be part of higher level bindings with shorter and schemier name conventions in order to feel more natural.

**Comment by LiberalArtist** [comment]
Agreed that these names are not great. In general, with FFI packages, I think it works nicely to have a core layer that basically lets you program at the level of the C API, but taking advantage of `ffi/unsafe`'s ability to manage things like output arguments and automatic finalization. Then people have some freedom to experiment with writing higher-level Racket APIs. I generally like to use the C-style name for things that are actually part of the C API and idiomatic Racket names for things that  exist only at the Racket level.

**Comment by guygastineau** [comment]
@LiberalArtist Yes, thank you for your perspective.

As I thought more about this I realized that this package is intended to be very literal in relation to the C API.

I like the idea of leaving it open for higher level wrappers.  Still, most people writing higher level wrappers might prefer a friendlier intermediate set of bindings.  Perhaps I am thinking that this project deserves a fairly closely coupled project that generates a friendlier interface that is still very shallow, but which is easier as the foundational layer for high level APIs.  I still don't have a really clear idea what that would be.  Regardless, its demands on this project would be very little except asking for consistency in the naming conventions.

I also really like Guile (which has pretty good `libgit2` bindings).  The guile-git library uses more schemey names, but the bindings are still pretty literal relative to the C API.  I would also like to make a `r6rs` library that sort of unifies and schemifies the facilities from libgit2.  In any case, I am getting ahead of myself here.

Anyway, are you still interested in finishing #4 ?
I imagine we should hold off on fixing the names to adhere more strictly to the C API until you have those changes in so you don't have to slog through a mountain of merge conflicts.  I am flexible, so let me know your preference.

At some point if everyone is okay with it I would like to remove all trailing whitespace in one go.

Then I imagine we could try just to get the naming convention all consitent with C (I do think it might be nice to use `prefix-out` to do some `<prefix>:` stuff and shorten some names, but that can probably be generated in some wrappers around this if it doesn't belong in this package.  During the naming unification I think the test suite should only be modified to fix any breaking changes.

After all that, we should be in a good place to make an organized, comprehensive test suite out of what is already there.

I just let some of this free flow with probably insufficient thought.  Let me know what you agree with or how you envision some of this work for the future of the package.  I am keen to get your perspective ;)

**Comment by jbclements** [comment]
Merged @LiberalArtist 's pull request (#4), would it make sense to close this issue now?

**Comment by LiberalArtist** [comment]
There's certainly still work to be done on the points raised here, but, especially since we're moving to https://github.com/libgit2-racket/libgit2, I think it makes sense to close this and welcome reports about remaining infelicitous names over there.

**Comment by jbclements** [comment]
literal lol

**Comment by jbclements** [comment]
closing
